// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZlVPY2jVQmSYafQRJgdr4T645AhkScY',
    appId: '1:945358288281:web:2b5c93e1f29f5a81b34f08',
    messagingSenderId: '945358288281',
    projectId: 'kids-learning-platform-6266f',
    authDomain: 'kids-learning-platform-6266f.firebaseapp.com',
    storageBucket: 'kids-learning-platform-6266f.firebasestorage.app',
    measurementId: 'G-GTNS7DT9FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE929pMaWiHL3CRVTcdwkAsaBAzjqMygk',
    appId: '1:945358288281:android:fa9d4c53caddccfeb34f08',
    messagingSenderId: '945358288281',
    projectId: 'kids-learning-platform-6266f',
    storageBucket: 'kids-learning-platform-6266f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDex78AuL9t2rccJc3x-g9waujph27LmqQ',
    appId: '1:945358288281:ios:787448950475c087b34f08',
    messagingSenderId: '945358288281',
    projectId: 'kids-learning-platform-6266f',
    storageBucket: 'kids-learning-platform-6266f.firebasestorage.app',
    iosBundleId: 'com.example.flutterLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAZlVPY2jVQmSYafQRJgdr4T645AhkScY',
    appId: '1:945358288281:web:7ab08922aecc20bfb34f08',
    messagingSenderId: '945358288281',
    projectId: 'kids-learning-platform-6266f',
    authDomain: 'kids-learning-platform-6266f.firebaseapp.com',
    storageBucket: 'kids-learning-platform-6266f.firebasestorage.app',
    measurementId: 'G-KZDHDN71SJ',
  );
}
